import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'screens/completion/completion_screen.dart';
import 'screens/drawing/drawing_screen.dart';
import 'screens/gallery/gallery_screen.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/story_completion/story_completion_screen.dart';
import 'screens/story_selection/story_selection_screen.dart';
import 'screens/story_transition/transition_screen.dart';
import 'screens/welcome/welcome_screen.dart';
import 'services/progress_service.dart';

// Generated by `flutter gen-l10n`
import 'l10n/app_localizations.dart';

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------
final _router = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const SplashScreen(),
    ),
    GoRoute(
      path: '/onboarding',
      builder: (context, state) => const OnboardingScreen(),
    ),
    GoRoute(
      path: '/stories',
      builder: (context, state) => const StorySelectionScreen(),
    ),
    GoRoute(
      path: '/drawing/:drawingId',
      builder: (context, state) {
        final drawingId = state.pathParameters['drawingId']!;
        return DrawingScreen(key: ValueKey(drawingId), drawingId: drawingId);
      },
    ),
    GoRoute(
      path: '/completion/:drawingId',
      pageBuilder: (context, state) {
        final drawingId = state.pathParameters['drawingId']!;
        final skipReveal =
            state.uri.queryParameters['skipReveal'] == 'true';
        final elapsedMs = int.tryParse(
          state.uri.queryParameters['elapsedMs'] ?? '',
        );
        return CustomTransitionPage(
          key: state.pageKey,
          child: CompletionScreen(
              drawingId: drawingId,
              skipReveal: skipReveal,
              elapsedMs: elapsedMs),
          transitionsBuilder:
              (context, animation, secondaryAnimation, child) =>
                  FadeTransition(opacity: animation, child: child),
          transitionDuration: const Duration(milliseconds: 600),
          reverseTransitionDuration: const Duration(milliseconds: 300),
        );
      },
    ),
    GoRoute(
      path: '/transition/:storyId/:chapterIndex',
      builder: (context, state) {
        final storyId = state.pathParameters['storyId']!;
        final chapterIndex =
            int.tryParse(state.pathParameters['chapterIndex'] ?? '0') ?? 0;
        return TransitionScreen(storyId: storyId, chapterIndex: chapterIndex);
      },
    ),
    GoRoute(
      path: '/story-complete/:storyId',
      builder: (context, state) {
        final storyId = state.pathParameters['storyId']!;
        return StoryCompletionScreen(storyId: storyId);
      },
    ),
    GoRoute(
      path: '/gallery',
      builder: (context, state) => const GalleryScreen(),
    ),
    GoRoute(
      path: '/welcome',
      builder: (context, state) => const WelcomeScreen(),
    ),
  ],
);

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------
class DotStoryApp extends ConsumerWidget {
  const DotStoryApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      title: 'Dot Story',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF6B4EFF),
          secondary: const Color(0xFFFF9F43),
        ),
        fontFamily: 'Roboto',
      ),
      routerConfig: _router,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('he'),
        Locale('ar'),
      ],
      locale: _localeFromLanguage(
        ref.watch(progressProvider).selectedLanguage,
      ),
    );
  }

  Locale _localeFromLanguage(String lang) {
    switch (lang) {
      case 'he':
        return const Locale('he');
      case 'ar':
        return const Locale('ar');
      default:
        return const Locale('en');
    }
  }
}

// ---------------------------------------------------------------------------
// SplashScreen
// ---------------------------------------------------------------------------
class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({super.key});

  @override
  ConsumerState<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends ConsumerState<SplashScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      final progress = ref.read(progressProvider);
      if (progress.onboardingComplete) {
        context.go('/welcome');
      } else {
        context.go('/onboarding');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Color(0xFF6B4EFF),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.star, size: 80, color: Colors.white),
            SizedBox(height: 16),
            Text(
              'Dot Story',
              style: TextStyle(
                fontSize: 48,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
